export const ADD_HISTORY_BOARD = 'BOARDS/ADD_HISTORY_BOARD';
export const RESET_HISTORY_BOARD = 'BOARDS/RESET_HISTORY_BOARD';
export const RESET_SCORE = 'BOARDS/RESET_SCORE';
export const GET_HISTORY_STEP = 'BOARDS/GET_HISTORY_STEP';
