export const HISTORY = 'BOARDS/HISTORY';
export const STEP_NUMBER = 'BOARDS/STEP_NUMBER';
export const IS_ASCENDING = 'BOARDS/IS_ASCENDING';
export const X_IS_NEXT = 'BOARDS/X_IS_NEXT';
export const SET_X_IS_NEXT = 'BOARDS/SET_X_IS_NEXT';
/** NEW */
export const ADD_HISTORY_BOARD = 'BOARDS/ADD_HISTORY_BOARD';
export const GET_HISTORY_STEP = 'BOARDS/GET_HISTORY_STEP';
